version: '3.8'

services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: smart-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongo:
    image: mongo
    container_name: smart-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  neo4j:
    image: neo4j
    container_name: smart-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

volumes:
  mongo_data:
  neo4j_data:
